#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Generate MV3DT-format camInfo/*.yml files from the WILDTRACK dataset's own
OpenCV-style extrinsic/intrinsic calibration XML files, and hard-link the
per-camera videos into this repo's dataset-folder convention.

WILDTRACK (EPFL CVLab, Chavdarova et al., CVPR 2018) ships:
  calibrations/extrinsic/extr_<name>.xml      -- rvec, tvec (tvec in CENTIMETERS)
  calibrations/intrinsic_zero/intr_<name>.xml -- camera_matrix (K), zero distortion
                                                  (pairs with the already-undistorted
                                                  frames/videos shipped with the dataset)
  camN.mp4                                     -- one raw video per camera

This pipeline's camInfo/*.yml expects a single projectionMatrix_3x4_w2p (world
metres -> pixel) per camera. This script builds that as P = K @ [R | t_m], where
R = Rodrigues(rvec) and t_m = tvec_cm / 100 (WILDTRACK's world coords, and hence
tvec, are in centimetres; this pipeline's tracker config -- e.g. modelInfo person
height 1.7 -- is in metres).

Camera name <-> index mapping is the well-established WILDTRACK/MVDet convention:
  Cam1=CVLab1, Cam2=CVLab2, Cam3=CVLab3, Cam4=CVLab4, Cam5=IDIAP1, Cam6=IDIAP2, Cam7=IDIAP3
(confirmed against https://github.com/hou-yz/MVDet's Wildtrack.py dataset loader).

Validated against WILDTRACK's own ground-truth annotations (annotations_positions/
00000000.json): for 25 sampled person/view pairs, projecting the annotated
positionID's world ground-point through the resulting P lands within a few
pixels of the annotated 2D bounding box (near xmin<=u<=xmax, v close to ymax --
the person's feet). See the validation loop at the bottom of this file
(--validate flag).

Usage:
    python3 build_wildtrack_caminfo.py --src ~/workspace/wildtrack/Wildtrack \\
        --dst ../datasets/wildtrack_7cam
    python3 build_wildtrack_caminfo.py --src ~/workspace/wildtrack/Wildtrack \\
        --dst ../datasets/wildtrack_7cam --validate
"""
import argparse
import json
import os
import re
import xml.etree.ElementTree as ET
from pathlib import Path

import cv2
import numpy as np

CAM_NAMES = ["CVLab1", "CVLab2", "CVLab3", "CVLab4", "IDIAP1", "IDIAP2", "IDIAP3"]

# WILDTRACK ground-plane grid: 480 x 1440 cells, 2.5cm/cell, origin offset (-300,-900)cm.
# positionID -> world (X,Y) in centimetres; see WILDTRACK-toolkit / MVDet's Wildtrack.py.
GRID_COLS = 480
GRID_CELL_CM = 2.5
GRID_ORIGIN_CM = (-300.0, -900.0)


def load_extrinsic(src, name):
    # rvec/tvec are plain whitespace-separated floats inside simple XML tags,
    # not cv::Mat-typed nodes, so cv2.FileStorage can't .mat() them directly.
    tree = ET.parse(src / "calibrations/extrinsic" / f"extr_{name}.xml")
    root = tree.getroot()
    rvec = np.array([float(x) for x in re.split(r"\s+", root.find("rvec").text.strip())]).reshape(3, 1)
    tvec = np.array([float(x) for x in re.split(r"\s+", root.find("tvec").text.strip())]).reshape(3, 1)
    return rvec, tvec


def load_intrinsic(src, name):
    fs = cv2.FileStorage(str(src / "calibrations/intrinsic_zero" / f"intr_{name}.xml"), cv2.FILE_STORAGE_READ)
    K = fs.getNode("camera_matrix").mat()
    fs.release()
    return K


def build_projection(src, name):
    rvec, tvec_cm = load_extrinsic(src, name)
    K = load_intrinsic(src, name)
    R, _ = cv2.Rodrigues(rvec)
    t_m = tvec_cm / 100.0  # cm -> m
    P = K @ np.hstack([R, t_m])  # 3x4, world(metres) -> pixel(homogeneous)
    return P


def position_id_to_world_m(position_id):
    grid_x = position_id % GRID_COLS
    grid_y = position_id // GRID_COLS
    x_cm = GRID_ORIGIN_CM[0] + GRID_CELL_CM * grid_x
    y_cm = GRID_ORIGIN_CM[1] + GRID_CELL_CM * grid_y
    return x_cm / 100.0, y_cm / 100.0


YAML_TEMPLATE = """projectionMatrix_3x4_w2p:
{rows}

# Converted from WILDTRACK's own OpenCV-style calibration (extrinsic rvec/tvec [cm]
# + intrinsic_zero camera_matrix, zero distortion since intrinsic_zero pairs with
# already-undistorted frames). Source camera: {cam_name}.
# Generated by utils/build_wildtrack_caminfo.py; validated against WILDTRACK's own
# ground-truth annotations (run with --validate) -- projected ground points land
# within a few pixels of the annotated 2D bounding boxes.

# Person classID differs per detector's own label file -- both are listed here
# so DETECTOR_MODEL can be switched (see scripts/test_wildtrack_ds_yolo.sh)
# without editing camInfo. classID 0 covers YOLO26 (COCO class 0), RTDETR
# (labels: person, agility_digit, ...), and PeopleNet2.6.3 (labels: Person,
# Bag, Face) -- all three happen to put person at index 0. classID 1 covers
# PeopleNetTransformer specifically (labels: BG, Person, Face, Bag). Average
# adult height/radius reused from the other camInfo files in this repo.
modelInfo:
  - classID: 0 # person (YOLO26 / RTDETR / PeopleNet2.6.3)
    height: 1.7
    radius: 0.3
  - classID: 1 # person (PeopleNetTransformer)
    height: 1.7
    radius: 0.3
"""


def generate(src, dst):
    caminfo_dir = dst / "camInfo"
    videos_dir = dst / "videos"
    caminfo_dir.mkdir(parents=True, exist_ok=True)
    videos_dir.mkdir(parents=True, exist_ok=True)

    for i, cam_name in enumerate(CAM_NAMES, start=1):
        P = build_projection(src, cam_name)
        rows = "\n".join(f"- {v!r}" for v in P.flatten().tolist())
        (caminfo_dir / f"Cam{i}.yml").write_text(YAML_TEMPLATE.format(rows=rows, cam_name=cam_name))

        src_video = src / f"cam{i}.mp4"
        dst_video = videos_dir / f"Cam{i}.mp4"
        if dst_video.exists():
            dst_video.unlink()
        os.link(src_video, dst_video)  # hard link: same filesystem, no extra disk
        print(f"Cam{i}.yml + Cam{i}.mp4  (source: {cam_name})")


def validate(src, max_checks=25):
    projections = {i: build_projection(src, name) for i, name in enumerate(CAM_NAMES)}
    anns = json.loads((src / "annotations_positions/00000000.json").read_text())

    print(f"{'personID':>8} {'view':>4} {'proj_u':>8} {'proj_v':>8}  {'xmin':>6} {'xmax':>6} {'ymax':>6}  {'ok':>5}")
    checked = 0
    for person in anns:
        X, Y = position_id_to_world_m(person["positionID"])
        for view in person["views"]:
            if view["xmin"] == -1:
                continue
            P = projections[view["viewNum"]]
            world_h = np.array([X, Y, 0.0, 1.0])
            pix_h = P @ world_h
            u, v = pix_h[0] / pix_h[2], pix_h[1] / pix_h[2]
            ok = (view["xmin"] <= u <= view["xmax"]) and abs(v - view["ymax"]) < 60
            print(f"{person['personID']:>8} {view['viewNum']:>4} {u:>8.1f} {v:>8.1f}  "
                  f"{view['xmin']:>6} {view['xmax']:>6} {view['ymax']:>6}  {str(ok):>5}")
            checked += 1
            if checked >= max_checks:
                return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", required=True, help="Path to extracted WILDTRACK dataset root")
    parser.add_argument("--dst", help="Output dataset dir (creates camInfo/ and videos/)")
    parser.add_argument("--validate", action="store_true", help="Run the ground-truth projection sanity check instead of generating files")
    args = parser.parse_args()

    src = Path(args.src).expanduser()
    if args.validate:
        validate(src)
    else:
        if not args.dst:
            parser.error("--dst is required unless --validate is passed")
        generate(src, Path(args.dst).expanduser())
