# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Runs the MV3DT pipeline on the 7-camera WILDTRACK dataset
# (see datasets/wildtrack_7cam/, generated by utils/build_wildtrack_caminfo.py).
#
# Unlike the 4cam/12cam scripts, this dataset has no map.png/transforms.yml
# (WILDTRACK ships ground-plane annotations, not a floorplan image), so the
# real-time BEV visualizer is skipped -- use the tracker-kitti-dump output and
# annotations_positions/ ground truth for evaluation instead. Runs with the
# tracker override in config_templates/override_tracker_wildtrack.yml (lowers
# minPoseConfidence -- see that file for why). Writes the tiled output to
# <experiment-dir>/outVideos/tiled_display_raw.mp4 instead of a live OSD
# window, since a live window can lag/backpressure the pipeline on a slow or
# virtual display.

# Select dataset variant: "short" (default) is a 210s/~30fps trim of all 7
# cameras (see datasets/wildtrack_7cam_short/README.md) -- covers all of
# WILDTRACK's own ground-truth annotation frames (which end at 199.5s) at
# roughly 1/12 the frame count of the full recordings, so iteration is fast.
# "full" is the original ~35min/59.94fps recordings -- slow, mainly useful for
# an eventual full end-to-end pass once the short-clip results look right.
export WILDTRACK_DATASET=${WILDTRACK_DATASET:-short}

if [[ "$WILDTRACK_DATASET" = "full" ]]; then
    export DATASET_DIR=$PWD/datasets/wildtrack_7cam/
    export EXPERIMENT_DIR=$PWD/experiments/deepstream/wildtrack_7cam
else
    export DATASET_DIR=$PWD/datasets/wildtrack_7cam_short/
    export EXPERIMENT_DIR=$PWD/experiments/deepstream/wildtrack_7cam_short
fi
export MODEL_REPO=$PWD/models

# Select detector model: PeopleNetTransformer (default), RTDETR, PeopleNet2.6.3, Yolo26n, or Yolo26m
export DETECTOR_MODEL=${DETECTOR_MODEL:-PeopleNetTransformer}

if [[ "$DETECTOR_MODEL" = "RTDETR" ]]; then
    DETECTOR_CONFIG="config_pgie_rt_detr.txt"
    TRACKER_CONFIG="config_tracker.yml"
elif [[ "$DETECTOR_MODEL" = "PeopleNet2.6.3" ]]; then
    DETECTOR_CONFIG="config_pgie_peoplenet.txt"
    TRACKER_CONFIG="config_tracker.yml"
elif [[ "$DETECTOR_MODEL" = "Yolo26n" ]]; then
    DETECTOR_CONFIG="config_pgie_yolo26n.txt"
    TRACKER_CONFIG="config_tracker.yml"
elif [[ "$DETECTOR_MODEL" = "Yolo26m" ]]; then
    DETECTOR_CONFIG="config_pgie_yolo26m.txt"
    TRACKER_CONFIG="config_tracker.yml"
else
    DETECTOR_CONFIG="config_pgie.txt"
    TRACKER_CONFIG="config_tracker.yml"
fi

echo "Using dataset: $WILDTRACK_DATASET ($DATASET_DIR)"
echo "Using detector model: $DETECTOR_MODEL (detector=$DETECTOR_CONFIG, tracker=$TRACKER_CONFIG)"

# Set correct GPU flag considering diffent platforms
if docker info | grep -q 'Runtimes.*nvidia'; then
    GPU_FLAG="--runtime=nvidia"
elif docker run --help | grep -q -- "--gpus"; then
    GPU_FLAG="--gpus all"
else
    echo "No GPU support found in Docker."
    exit 1
fi

# Create directories for output
mkdir -p $EXPERIMENT_DIR/infer-kitti-dump
mkdir -p $EXPERIMENT_DIR/tracker-kitti-dump
mkdir -p $EXPERIMENT_DIR/outVideos

# Auto-generate DeepStream configuration files
# --config-overrides lowers ObjectModelProjection.minPoseConfidence: the base
# config_tracker.yml's default (0.925) was tuned against the synthetic
# warehouse dataset's clean renders and rejects essentially every pose
# estimate on WILDTRACK's real, compressed photographic footage -- see
# config_templates/override_tracker_wildtrack.yml for details.
source mv3dt_venv/bin/activate
python utils/deepstream_auto_configurator.py \
    --dataset-dir=$DATASET_DIR \
    --enable-msg-broker \
    --enable-file-output \
    --detector-config=$DETECTOR_CONFIG \
    --tracker-config=$TRACKER_CONFIG \
    --config-overrides=override_tracker_wildtrack.yml \
    --output-dir=$EXPERIMENT_DIR

# Launch MV3DT pipeline
docker run -t --privileged --rm --net=host $GPU_FLAG \
    -v $MODEL_REPO:/workspace/models \
    -v $DATASET_DIR:/workspace/inputs \
    -v $EXPERIMENT_DIR:/workspace/experiments \
    -v $HOME/workspace/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo:/workspace/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo \
    -v /tmp/.X11-unix/:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -w /workspace/experiments \
    ${DEEPSTREAM_IMAGE:-nvcr.io/nvidia/deepstream:9.1-triton-multiarch} \
    deepstream-test5-app -c config_deepstream.txt
